name: pdbinf
channels:
  - conda-forge
dependencies:
  - coverage
  - numpy
  - pip
  - pytest
  - pytest-cov
  - pytest-xdist
  - typing-extensions
  - gemmi
  - rdkit
  # docs
  - myst-parser
  - pydata-sphinx-theme
